# Generated by Django 3.0 on 2019-12-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_is_ative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='is_ative',
        ),
    ]
